### PR TITLE
Indenting issues within ShowContAll

### PR DESCRIPTION
**Pull request by NotAProfessionalDeveloper**
The "if" block in question in indented further than required. That makes the code very hard to read.

### CODE REVIEW

**Comment by haussli** [comment]
Please provide an example of the input from the cli.

**Comment by NotAProfessionalDeveloper** [comment]
What I meant was the indenting in the code needed fixing. See my patch.

**Comment by haussli** [comment]
Ah, ok.  thanks

**Comment by NotAProfessionalDeveloper** [comment]
Any reason why this wasn't merged? Thanks.

**Pull request closed without merging**
